### ISSUE TITLE
two nzbget processes are run on startup

### ISSUE THREAD

**Issue by hlarsen** [binhex/arch-nzbget#1]
after the container starts there are two nzbget processes running:

>\# ps aux | grep nzbget
>nobody      20  0.0  0.0 315140  4048 ?        Ssl  22:56   0:00 /usr/bin/nzbget -D -c /config/nzbget.conf
>nobody      41  0.0  0.0 179964  3540 ?        Ssl  22:56   0:00 /usr/bin/nzbget -D -c /config/nzbget.conf

this causes an error to endlessly repeat in the nzbget logs:

> ERROR   Binding socket failed for 0.0.0.0: ErrNo 98, Address already in use

it appears to be happening because start.sh is calling nzbget in daemon mode, resulting in supervisor thinking the process is dead and eventually giving up with two processing still running:

>2016-10-05 22:42:55,838 INFO exited: nzbget (exit status 0; not expected)
>2016-10-05 22:42:55,838 DEBG received SIGCLD indicating a child quit
>2016-10-05 22:42:55,839 INFO gave up: nzbget entered FATAL state, too many start retries too quickly

running nzbget in console mode results in only one process starting, however the interactive nature of the console pollutes supervisord.log.

**Comment by binhex** [comment]
Thanks for bringing this to my attention, this is now fixed and a new image has been generated.
