### ISSUE TITLE
Error: 404 Not Found after docker pull update

### ISSUE THREAD

**Issue by ibasaw** [binhex/arch-nzbget#3]
i had update this morning and got this on front

Error: 404 Not Found

**Comment by binhex** [comment]
See here https://r.tapatalk.com/shareLink?url=https://lime-technology.com/forums/topic/44140-support-binhex-nzbget/?do=findComment&comment=672157&share_tid=44140&share_pid=672157&share_fid=18593&share_type=t

**Comment by ibasaw** [comment]
this is the config file which is not correct for the new version

**Comment by binhex** [comment]
This should now be fixed up.

**Comment by ibasaw** [comment]
thank you
